# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in this Gemfile
#   gem "sqlite3"
#
ddefault: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: meeting_scheduler_development

test:
  <<: *default
  database: meeting_scheduler_test

production:
  <<: *default
  database: meeting_scheduler_production
  username: meeting_scheduler
  password: <%= ENV['MEETING_SCHEDULER_DATABASE_PASSWORD'] %>